## Colors configuration
colors:
  # Default colors
  primary:
    background: '#030315'
    foreground: '#cdc7d3'

  # Normal colors
  normal:
    black:   '#19192D'
    red:     '#553B88'
    green:   '#364995'
    yellow:  '#60559D'
    blue:    '#9F6495'
    magenta: '#CB7192'
    cyan:    '#00ddff'
    white:   '#cdc7d3'

  # Bright colors
  bright:
    black:   '#8f8b93'
    red:     '#553B88'
    green:   '#364995'
    yellow:  '#60559D'
    blue:    '#9F6495'
    magenta: '#CB7192'
    cyan:    '#00ddff'
    white:   '#cdc7d3'
