## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

# Font configuration
font:
  # Point size
  size: 13

  # Offset
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0
