#! /bin/sh

## Start up
$HOME/.config/bspwm/startup.sh

## Set Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

## Configuration
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Windows Rules
# bspc rule -a [app(wm_name)name] desktop='^[number of desktop]' state=floating manage=on
